version: '2'

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:9.6-debian-10'
    ports:
      - '1111:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=pass
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=db
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=${SYNC_MODE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
  postgresql-slave:
    image: 'docker.io/bitnami/postgresql:9.6-debian-10'
    ports:
      - '2222:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=pass
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=db

volumes:
  postgresql_master_data:
    driver: local
